// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcvtqeftwajyhtthdbaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjdnRxZWZ0d2FqeWh0dGhkYmF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MDQ4NTcsImV4cCI6MjA4NjQ4MDg1N30.7p4IoE696D9f7iyKq48mDs2ilSKje31V_12XSU7oohA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});